project:

  name: acne04-classification-optimized
  seed: 42
  output_dir: outputs
  checkpoints_dir: checkpoints
  logs_dir: logs

data:
  train_dir: data/processed/acne04/train
  val_dir: data/processed/acne04/val
  num_classes: 4  # adjust to your Acne04 label set
  img_size: 224
  num_workers: 4

  sampler: weighted  # none|weighted

train:


  model: efficientnet_b3
  pretrained: true
  epochs: 50
  batch_size: 16
  lr: 0.0005


  weight_decay: 0.01
  optimizer: adamw
  scheduler: cosine
  loss: focal           # focal|cross_entropy
  class_weights: auto   # auto|none|[w0,w1,w2,w3]
  mixup: 0.2


  cutmix: 0.2

aug:
  hflip: 0.5
  vflip: 0.15
  color_jitter: [0.3, 0.3, 0.3, 0.15]
  random_erasing: 0.25
  rotate: 30           # degrees


  affine: [0.1, 10]    # translate (fraction), shear (deg)

infer:


  tta: 4

