project:

  name: acne04-classification-optimized
  seed: 42
  output_dir: outputs
  checkpoints_dir: checkpoints
  logs_dir: logs

data:
  train_dir: data/processed/acne04/train
  val_dir: data/processed/acne04/val
  num_classes: 4  # adjust to your Acne04 label set
  img_size: 224
  num_workers: 4

  sampler: weighted_plus  # none|weighted|weighted_plus
  oversample_factors: [1.0, 1.0, 3.0, 3.5]
  minority_aug: true
  hard_mining: true  # focus on Moderate/Severe boundary

train:


  model: efficientnet_b3_cbam
  pretrained: true
  epochs: 80
  batch_size: 16
  lr: 0.0003


  weight_decay: 0.01
  optimizer: adamw
  scheduler: cosine_warmup
  warmup_epochs: 5
  loss: boundary_aware_focal
  class_weights: [1.0, 1.2, 3.2, 2.5]
  focal_gamma: [2.0, 2.2, 3.2, 2.8]
  confusion_penalty: 2.0  # extra penalty for Moderate<->Severe confusion
  mixup: 0.05


  cutmix: 0.05
  label_smoothing: 0.05

aug:
  hflip: 0.5
  vflip: 0.15
  color_jitter: [0.3, 0.3, 0.3, 0.15]
  random_erasing: 0.25
  rotate: 30           # degrees


  affine: [0.1, 10]    # translate (fraction), shear (deg)

infer:


  tta: 4

